import obsidianmd from "eslint-plugin-obsidianmd";
import tseslint from "typescript-eslint";

export default tseslint.config(
  ...obsidianmd.configs.recommended,
  {
    files: ["src/**/*.ts"],
    languageOptions: {
      parserOptions: {
        project: true,
        tsconfigRootDir: import.meta.dirname,
      },
    },
    rules: {
      "obsidianmd/ui/sentence-case": [
        "error",
        {
          enforceCamelCaseLower: true,
          acronyms: [
            "API",
            "HTTP",
            "HTTPS",
            "URL",
            "DNS",
            "TCP",
            "IP",
            "SSH",
            "TLS",
            "SSL",
            "FTP",
            "SFTP",
            "SMTP",
            "JSON",
            "XML",
            "HTML",
            "CSS",
            "PDF",
            "CSV",
            "YAML",
            "SQL",
            "PNG",
            "JPG",
            "JPEG",
            "GIF",
            "SVG",
            "2FA",
            "MFA",
            "OAuth",
            "JWT",
            "LDAP",
            "SAML",
            "SDK",
            "IDE",
            "CLI",
            "GUI",
            "CRUD",
            "SOAP",
            "CPU",
            "GPU",
            "RAM",
            "SSD",
            "USB",
            "UI",
            "OK",
            "RSS",
            "S3",
            "ID",
            "UUID",
            "GUID",
            "SHA",
            "MD5",
            "ASCII",
            "UTF-8",
            "UTF-16",
            "DOM",
            "CDN",
            "FAQ",
            "AI",
            "ML",
            "LLM",
            "PO",
            "POT",
          ],
        },
      ],
    },
  },
  {
    ignores: ["dist/**", "node_modules/**", "*.js", "*.mjs", "scripts/**", "docs/**"],
  },
);
